#!/usr/bin/env python3
"""
Cross-Reference Builder for Stray Dogs Worldengine
Analyzes all files and builds relationship maps
"""

import re
from pathlib import Path
from typing import Dict, Set, List
from collections import defaultdict

# Configuration
REPO_ROOT = Path(__file__).parent.parent
CHARS_DIR = REPO_ROOT / "chars"
LOCATIONS_DIR = REPO_ROOT / "locations"
FACTIONS_DIR = REPO_ROOT / "factions"
OUTPUT_FILE = REPO_ROOT / "meta" / "cross_reference.md"

try:
    from colors import Colors
except ImportError:
    from scripts.colors import Colors

def extract_yaml_tags(filepath: Path) -> Dict[str, List[str]]:
    """Extract tags from YAML frontmatter"""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        yaml_match = re.search(r'^---\n(.*?)\n---', content, re.MULTILINE | re.DOTALL)
        if not yaml_match:
            return {}

        yaml_content = yaml_match.group(1)
        if not yaml_content.endswith('\n'):
            yaml_content += '\n'

        # Extract tags section
        tags_match = re.search(r'tags:\s*\n((?:  .*\n)*)', yaml_content)
        if not tags_match:
            return {}

        tags_section = tags_match.group(1)

        # Parse tag categories
        tag_dict = {}
        current_category = None

        for line in tags_section.split('\n'):
            if ':' in line and line.strip().endswith(':'):
                # Category line
                current_category = line.split(':')[0].strip()
                tag_dict[current_category] = []
            elif current_category and '#' in line:
                # Tag line
                tags = re.findall(r'#\w+', line)
                tag_dict[current_category].extend(tags)

        return tag_dict

    except Exception as e:
        print(f"{Colors.RED}Error reading {filepath}: {e}{Colors.RESET}")
        return {}

def build_character_location_map() -> Dict[str, Dict[str, Set[str]]]:
    """Build map of characters to locations and vice versa"""
    char_to_locations = defaultdict(set)
    location_to_chars = defaultdict(set)

    # Scan all character files
    for char_file in CHARS_DIR.rglob("*.md"):
        if '00_' in char_file.name:
            continue

        tags = extract_yaml_tags(char_file)
        char_tag = tags.get('character', [''])[0] if 'character' in tags else ''

        if char_tag and 'locations' in tags:
            for loc_tag in tags['locations']:
                char_to_locations[char_tag].add(loc_tag)
                location_to_chars[loc_tag].add(char_tag)

    return {
        'char_to_locations': dict(char_to_locations),
        'location_to_chars': dict(location_to_chars)
    }

def build_relationship_map() -> Dict[str, Set[str]]:
    """Build map of character relationships"""
    relationships = defaultdict(set)

    for char_file in CHARS_DIR.rglob("*.md"):
        if '00_' in char_file.name:
            continue

        tags = extract_yaml_tags(char_file)
        char_tag = tags.get('character', [''])[0] if 'character' in tags else ''

        if char_tag and 'relationships' in tags:
            for rel_tag in tags['relationships']:
                relationships[char_tag].add(rel_tag)
                # Bidirectional
                relationships[rel_tag].add(char_tag)

    return dict(relationships)

def generate_cross_reference():
    """Generate complete cross-reference markdown"""
    print(f"\n{Colors.BLUE}Building cross-reference map...{Colors.RESET}\n")

    loc_map = build_character_location_map()
    rel_map = build_relationship_map()

    output = []
    output.append("# Cross-Reference Map\n")
    output.append("**Auto-generated by cross_ref_builder.py**\n")
    output.append(f"**Generated**: {Path(__file__).stat().st_mtime}\n")
    output.append("---\n\n")

    # Character ↔ Location section
    output.append("## Character ↔ Location Relationships\n\n")
    for char, locations in sorted(loc_map['char_to_locations'].items()):
        output.append(f"### {char}\n")
        output.append("**Appears at**:\n")
        for loc in sorted(locations):
            output.append(f"- {loc}\n")
        output.append("\n")

    # Location ↔ Character section
    output.append("## Location ↔ Character Presence\n\n")
    for loc, characters in sorted(loc_map['location_to_chars'].items()):
        output.append(f"### {loc}\n")
        output.append("**Characters present**:\n")
        for char in sorted(characters):
            output.append(f"- {char}\n")
        output.append("\n")

    # Character ↔ Character section
    output.append("## Character ↔ Character Relationships\n\n")
    for char, related in sorted(rel_map.items()):
        output.append(f"### {char}\n")
        output.append("**Connected to**:\n")
        for rel in sorted(related):
            output.append(f"- {rel}\n")
        output.append("\n")

    # Write to file
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(''.join(output))

    print(f"{Colors.GREEN}✓ Cross-reference generated: {OUTPUT_FILE}{Colors.RESET}")
    print(f"{Colors.BLUE}  - Characters mapped: {len(loc_map['char_to_locations'])}{Colors.RESET}")
    print(f"{Colors.BLUE}  - Locations mapped: {len(loc_map['location_to_chars'])}{Colors.RESET}")
    print(f"{Colors.BLUE}  - Relationships: {len(rel_map)}{Colors.RESET}\n")

def main():
    """Main function"""
    print(f"\n{Colors.BLUE}{'='*60}{Colors.RESET}")
    print(f"{Colors.BLUE}STRAY DOGS WORLDENGINE - CROSS-REFERENCE BUILDER{Colors.RESET}")
    print(f"{Colors.BLUE}{'='*60}{Colors.RESET}")

    generate_cross_reference()

if __name__ == "__main__":
    main()
